version: '2'
services:
    conferencemanager-app:
        image: conferencemanager
        external_links:
            - mariadb:mariadb
            - kafka:kafka
            - zookeeper:zookeeper
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/conferencemanager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 9080:9080

networks:
  default:
    external:
      name: contosomiddleware_default
